const express = require('express');
const router = express.Router();
const { auth } = require('../middleware/auth');
const geminiService = require('../services/geminiService');
const callGeminiAPI = geminiService.default.callGeminiAPI;

const userJourneyProgress = {}; 

const predefinedJourneys = {
  anxiety: {
    id: 'anxiety',
    title: '7-Day Challenge to Reduce Anxiety',
    description: 'Complete one small task each day to build healthy habits.',
    tasks: [
      { task: "Practice 2 minutes of mindful breathing." },
      { task: "Write down three things you're grateful for." },
      { task: "Go for a 15-minute walk without your phone." },
      { task: "Listen to a calming music playlist." },
      { task: "Write down any worries, then close the notebook." },
      { task: "Reach out to a friend or family member." },
      { task: "Reflect on your progress this week." }
    ]
  },
  diet: {
    id: 'diet',
    title: '7-Day Healthy Diet Challenge',
    description: 'Fuel your body and mind with nutritious choices.',
    tasks: [
      { task: "Drink 8 glasses of water today." },
      { task: "Eat a piece of fruit with your breakfast." },
      { task: "Avoid sugary drinks for the whole day." },
      { task: "Include green vegetables in your dinner." },
      { task: "Try a healthy new recipe." },
      { task: "Avoid processed snacks for one day." },
      { task: "Plan one healthy meal for tomorrow." }
    ]
  },
  exercise: {
    id: 'exercise',
    title: '7-Day Daily Exercise Challenge',
    description: 'Get your body moving to boost your mood and energy.',
    tasks: [
      { task: "Do a 10-minute stretching session." },
      { task: "Go for a brisk 20-minute walk." },
      { task: "Try a 15-minute home workout video." },
      { task: "Take the stairs instead of the elevator all day." },
      { task: "Do 20 squats and 10 push-ups." },
      { task: "Play a sport or dance for 30 minutes." },
      { task: "Go for a light jog or long walk." }
    ]
  }
};

router.get('/', auth, (req, res) => {
    const userId = req.user.id;
    const journeysWithProgress = {};

    for (const key in predefinedJourneys) {
        const journey = predefinedJourneys[key];
        const progress = userJourneyProgress[userId]?.[journey.id] || [];
        journeysWithProgress[key] = {
            ...journey,
            tasks: journey.tasks.map((task, index) => ({
                ...task,
                completed: progress[index] || false
            }))
        };
    }
    res.json(journeysWithProgress);
});

router.post('/custom', auth, async (req, res) => {
    const { goal } = req.body;
    if (!goal) {
        return res.status(400).json({ msg: 'Goal is required' });
    }

    let aiResponseText = '';

    try {
        const prompt = `
            Act as an encouraging wellness coach. The user's goal is: "${goal}".
            Create a 7-day wellness plan with 7 simple, actionable tasks.
            List the 7 tasks clearly, one per line. Each line MUST start with "Day X: ".
            Do not include a title, description, or any other text. Just the 7 task lines.
        `;
        
        aiResponseText = await callGeminiAPI(prompt);

        const tasks = aiResponseText
            .split('\n')
            .map(line => line.trim())
            .filter(line => line.match(/^Day \d+:/i));

        if (tasks.length < 7) {
            throw new Error(`AI returned an insufficient number of tasks. Expected 7, got ${tasks.length}.`);
        }

        const newJourney = {
            id: `custom-${Date.now()}`,
            title: `Your 7-Day Plan: ${goal}`,
            description: `A personalized plan generated by AI to help you achieve your goal: "${goal}"`,
            tasks: tasks.slice(0, 7).map(task => ({
                task: task.replace(/^Day \d+: /i, '').trim(),
                completed: false
            }))
        };

        res.status(201).json(newJourney);

    } catch (err) {
        console.error("--- CUSTOM JOURNEY ERROR ---");
        console.error("User Goal:", goal);
        console.error("Raw AI Response:", aiResponseText);
        console.error("Error Details:", err.message);
        console.error("-----------------------------");
        res.status(500).send('Error generating custom plan from AI.');
    }
});

router.put('/:id', auth, async (req, res) => {
    const userId = req.user.id;
    const journeyId = req.params.id;
    const { tasks } = req.body;

    if (!tasks || !Array.isArray(tasks)) {
        return res.status(400).json({ msg: 'Tasks array is required' });
    }

    if (!userJourneyProgress[userId]) {
        userJourneyProgress[userId] = {};
    }

    userJourneyProgress[userId][journeyId] = tasks.map(t => !!t.completed);
    res.status(200).json({ msg: 'Progress saved' });
});

module.exports = router;
